import '../styles/globals.css'
import Search from '../components/layout/Search'
import Head from 'next/head'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import {ToastContainer} from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { app } from '../firebase.config'

import GlobalProvider from '../store'
function MyApp({ Component, pageProps }) {
  const App = app
  return (
  <GlobalProvider>
  <div className="App">
    <Head>
        <title>Cars For Sale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    
    <Component {...pageProps} />
    
  </div>
  <Footer />
  <ToastContainer />
  </GlobalProvider>)

}

export default MyApp
